# Task 1 — Inconsistencies and Duplicates

This notebook cleans the `club_signups.csv` dataset using pandas.

The goal is to produce one clean row per student per club while keeping the original CSV unchanged.

In [ ]:
import pandas as pd

In [19]:
raw = pd.read_csv("club_signups.csv")
df = raw.copy()
raw.head()

,signup_id,student_id,full_name,email,faculty,city,club,signed_up_at,fee_paid
0,S015,61-8942,Hana Zaki,hana.zaki@student.guc.edu.eg,Pharmacy,Giza,Soccer,2026-09-15 13:39,N
1,S010,61-3846,AHMED ZAKI,ahmed.zaki@student.guc.edu.eg,Management,alexandria,Chess,15/09/2026 03:12,false
2,S008,61-4844,Mohamed Adel,mohamed.adel@student.guc.edu.eg,EMS,Cairo,Music,2026-09-14 23:32,Y
3,S035,61-4844,MOHAMED ADEL,mohamed.adel@student.guc.edu.eg,Engineering and Materials Science,Cairo,Debating,2026-09-17 11:15,yes
4,S004,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Chess Club,2026-09-13 22:36,yes

## Part A — Inconsistencies

### A1. Inspect the raw data

In [9]:
print("Shape:", raw.shape)

Shape: (39, 9)

In [8]:
raw.dtypes

signup_id       object
student_id      object
full_name       object
email           object
faculty         object
city            object
club            object
signed_up_at    object
fee_paid        object
dtype: object

In [11]:
categorical_columns = [
    "signup_id",
    "student_id",
    "full_name",
    "email",
    "faculty",
    "city",
    "club",
    "fee_paid"
]

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(raw[column].value_counts(dropna=False))

--- signup_id ---
signup_id
S015    2
S022    2
S023    2
S028    1
S017    1
S031    1
S014    1
S011    1
S018    1
S030    1
S016    1
S029    1
S034    1
S009    1
S021    1
S013    1
S032    1
S019    1
S024    1
S010    1
S020    1
S008    1
S035    1
S004    1
S012    1
S007    1
S005    1
S033    1
S001    1
S003    1
S006    1
S026    1
S025    1
S002    1
S027    1
S036    1
Name: count, dtype: int64

--- student_id ---
student_id
61-7344    6
55-9245    5
61-4844    4
61-8942    3
58-1125    3
61-8224    3
61-2495    2
61-4733    2
55-2992    2
58-8701    2
58-1089    2
55-2639    2
61-3846    1
58-9118    1
55-2971    1
Name: count, dtype: int64

--- full_name ---
full_name
Laila Mostafa         4
Hana Zaki             3
Sara Zaki             3
Mohamed Adel          3
Ziad Saleh            3
Youssef Fathy         2
Karim Kamel           2
ali ibrahim           2
Ali Ibrahim           2
  Farida  Ibrahim     1
  Laila  Mostafa      1
Salma Ibrahim         1
Mariam Kamel          1
Farida Ibrahim        1
  Omar  Adel          1
mohamed adel          1
AHMED ZAKI            1
AHMED ADEL            1
OMAR ADEL             1
ahmed adel            1
ALI IBRAHIM           1
MOHAMED ADEL          1
  Mohamed  Adel       1
laila mostafa         1
Name: count, dtype: int64

--- email ---
email
ali.ibrahim@student.guc.edu.eg       5
mohamed.adel@student.guc.edu.eg      4
laila.mostafa@student.guc.edu.eg     4
hana.zaki@student.guc.edu.eg         3
ziad.saleh@student.guc.edu.eg        3
sara.zaki@student.guc.edu.eg         3
omar.adel@student.guc.edu.eg         2
farida.ibrahim@student.guc.edu.eg    2
LAILA.MOSTAFA@STUDENT.GUC.EDU.EG     2
karim.kamel@student.guc.edu.eg       2
youssef.fathy@student.guc.edu.eg     2
ahmed.adel@student.guc.edu.eg        1
AHMED.ADEL@STUDENT.GUC.EDU.EG        1
ahmed.zaki@student.guc.edu.eg        1
mariam.kamel@student.guc.edu.eg      1
salma.ibrahim@student.guc.edu.eg     1
MOHAMED.ADEL@STUDENT.GUC.EDU.EG      1
 mohamed.adel@student.guc.edu.eg     1
Name: count, dtype: int64

--- faculty ---
faculty
Pharmacy                                  7
EMS                                       7
IET                                       5
Management                                4
Information Engineering and Technology    4
MET                                       3
iet                                       3
Engineering and Materials Science         1
Pharma                                    1
met                                       1
Media Engineering and Technology          1
pharmacy                                  1
ems                                       1
Name: count, dtype: int64

--- city ---
city
Cairo         13
Alexandria    11
Giza           4
Alex           4
cairo          2
giza           2
alexandria     1
CAIRO          1
El Giza        1
Name: count, dtype: int64

--- club ---
club
Robotics       8
Music          5
Chess          4
football       4
Debating       3
Chess Club     3
Football       3
Soccer         2
music          2
chess          2
debate club    1
Music          1
Debate         1
Name: count, dtype: int64

--- fee_paid ---
fee_paid
yes      7
1        7
false    6
Y        5
N        4
TRUE     4
Yes      4
0        1
no       1
Name: count, dtype: int64

### A2. Clean faculty, club, and city

In [20]:
for column in ["faculty", "club", "city"]:
    df[column] = df[column].str.strip().str.lower()

In [13]:
for column in ["faculty", "club", "city"]:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False))

--- faculty ---
faculty
pharmacy                                  8
ems                                       8
iet                                       8
management                                4
met                                       4
information engineering and technology    4
engineering and materials science         1
pharma                                    1
media engineering and technology          1
Name: count, dtype: int64

--- club ---
club
music          8
robotics       8
football       7
chess          6
debating       3
chess club     3
soccer         2
debate club    1
debate         1
Name: count, dtype: int64

--- city ---
city
cairo         16
alexandria    12
giza           6
alex           4
el giza        1
Name: count, dtype: int64

In [21]:
faculty_map = {
    "met": "MET",
    "media engineering and technology": "MET",
    "iet": "IET",
    "information engineering and technology": "IET",
    "ems": "EMS",
    "engineering and materials science": "EMS",
    "pharmacy": "Pharmacy",
    "pharma": "Pharmacy",
    "management": "Management"
}

club_map = {
    "robotics": "Robotics",
    "debate": "Debate",
    "debating": "Debate",
    "debate club": "Debate",
    "music": "Music",
    "football": "Football",
    "soccer": "Football",
    "chess": "Chess",
    "chess club": "Chess"
}

city_map = {
    "cairo": "Cairo",
    "giza": "Giza",
    "el giza": "Giza",
    "alexandria": "Alexandria",
    "alex": "Alexandria"
}
df["faculty"] = df["faculty"].map(faculty_map)
df["club"] = df["club"].map(club_map)
df["city"] = df["city"].map(city_map)

In [22]:
for column in ["faculty", "club", "city"]:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False))

--- faculty ---
faculty
IET           12
Pharmacy       9
EMS            9
MET            5
Management     4
Name: count, dtype: int64

--- club ---
club
Football    9
Chess       9
Music       8
Robotics    8
Debate      5
Name: count, dtype: int64

--- city ---
city
Alexandria    16
Cairo         16
Giza           7
Name: count, dtype: int64

In [23]:
assert set(df["faculty"].dropna().unique()) <= {
    "MET", "IET", "EMS", "Pharmacy", "Management"
}

assert set(df["club"].dropna().unique()) <= {
    "Robotics", "Debate", "Music", "Football", "Chess"
}

assert set(df["city"].dropna().unique()) <= {
    "Cairo", "Giza", "Alexandria"
}

### A3. Clean names and emails

In [24]:
df["full_name"] = (
    df["full_name"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

df["email"] = (
    df["email"]
    .str.strip()
    .str.lower()
)

In [25]:
print(df["full_name"].value_counts(dropna=False))
print()
print(df["email"].value_counts(dropna=False))

full_name
Mohamed Adel      6
Laila Mostafa     6
Ali Ibrahim       5
Hana Zaki         3
Ziad Saleh        3
Sara Zaki         3
Ahmed Adel        2
Omar Adel         2
Farida Ibrahim    2
Karim Kamel       2
Youssef Fathy     2
Ahmed Zaki        1
Mariam Kamel      1
Salma Ibrahim     1
Name: count, dtype: int64

email
mohamed.adel@student.guc.edu.eg      6
laila.mostafa@student.guc.edu.eg     6
ali.ibrahim@student.guc.edu.eg       5
hana.zaki@student.guc.edu.eg         3
ziad.saleh@student.guc.edu.eg        3
sara.zaki@student.guc.edu.eg         3
ahmed.adel@student.guc.edu.eg        2
omar.adel@student.guc.edu.eg         2
farida.ibrahim@student.guc.edu.eg    2
karim.kamel@student.guc.edu.eg       2
youssef.fathy@student.guc.edu.eg     2
ahmed.zaki@student.guc.edu.eg        1
mariam.kamel@student.guc.edu.eg      1
salma.ibrahim@student.guc.edu.eg     1
Name: count, dtype: int64

### A4. Clean fee_paid

In [26]:
df["fee_paid"].value_counts(dropna=False)

fee_paid
yes      7
1        7
false    6
Y        5
N        4
TRUE     4
Yes      4
0        1
no       1
Name: count, dtype: int64

In [27]:
df["fee_paid"] = (
    df["fee_paid"]
    .str.strip()
    .str.lower()
)

fee_map = {
    "yes": True,
    "y": True,
    "true": True,
    "1": True,
    "no": False,
    "n": False,
    "false": False,
    "0": False
}

df["fee_paid"] = df["fee_paid"].map(fee_map)

In [28]:
df["fee_paid"].value_counts(dropna=False)

fee_paid
True     27
False    12
Name: count, dtype: int64

In [29]:
df["fee_paid"].dtype

dtype('bool')

### A5. Parse signed_up_at

In [30]:
df["signed_up_at"].value_counts(dropna=False)

signed_up_at
2026-09-15 13:39    2
2026-09-16 01:39    2
2026-09-16 09:29    2
2026-09-17 06:54    1
15/09/2026 18:01    1
2026-09-17 23:29    1
2026-09-15 11:36    1
15/09/2026 03:28    1
15/09/2026 18:40    1
2026-09-17 17:14    1
15/09/2026 17:20    1
17/09/2026 12:27    1
16/09/2026 02:01    1
2026-09-15 01:05    1
16/09/2026 01:15    1
2026-09-15 05:43    1
2026-09-17 23:36    1
15/09/2026 20:20    1
2026-09-16 16:16    1
15/09/2026 03:12    1
2026-09-15 23:07    1
2026-09-14 23:32    1
2026-09-17 11:15    1
2026-09-13 22:36    1
15/09/2026 03:42    1
2026-09-14 17:03    1
2026-09-13 23:52    1
2026-09-16 09:07    1
2026-09-13 14:36    1
2026-09-13 21:16    1
14/09/2026 01:22    1
16/09/2026 23:55    1
2026-09-16 20:31    1
13/09/2026 15:38    1
2026-09-17 00:41    1
18/09/2026 23:36    1
Name: count, dtype: int64

In [31]:
df["signed_up_at"] = pd.to_datetime(
    df["signed_up_at"],
    format="mixed",
    dayfirst=True
)

In [ ]:
df["signed_up_at"].head()

0   2026-09-15 13:39:00
1   2026-09-15 03:12:00
2   2026-09-14 23:32:00
3   2026-09-17 11:15:00
4   2026-09-13 22:36:00
Name: signed_up_at, dtype: datetime64[ns]

In [36]:
df["signed_up_at"].dtype

dtype('<M8[ns]')

In [37]:
assert pd.api.types.is_datetime64_any_dtype(df["signed_up_at"])
assert df["signed_up_at"].notna().all()

## Part B — Duplicates

### B1. Remove exact duplicates

In [38]:
exact_duplicates = df.duplicated().sum()
print("Exact duplicates:", exact_duplicates)

Exact duplicates: 3

In [39]:
before_exact = len(df)

df = df.drop_duplicates()

after_exact = len(df)

print("Rows before:", before_exact)
print("Exact duplicates removed:", before_exact - after_exact)
print("Rows after:", after_exact)

Rows before: 39
Exact duplicates removed: 3
Rows after: 36

### B2. Keep the latest submission per student and club

In [41]:
repeated_signups = df.duplicated(
    subset=["student_id", "club"],
    keep=False
)

df[repeated_signups].sort_values(
    ["student_id", "club", "signed_up_at"]
)

,signup_id,student_id,full_name,email,faculty,city,club,signed_up_at,fee_paid
8,S020,55-9245,Ali Ibrahim,ali.ibrahim@student.guc.edu.eg,MET,Cairo,Music,2026-09-15 23:07:00,False
9,S033,55-9245,Ali Ibrahim,ali.ibrahim@student.guc.edu.eg,MET,Cairo,Music,2026-09-16 09:07:00,True
22,S021,61-4844,Mohamed Adel,mohamed.adel@student.guc.edu.eg,EMS,Cairo,Debate,2026-09-16 01:15:00,False
3,S035,61-4844,Mohamed Adel,mohamed.adel@student.guc.edu.eg,EMS,Cairo,Debate,2026-09-17 11:15:00,True
35,S017,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Debate,2026-09-15 18:01:00,False
25,S034,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Debate,2026-09-16 02:01:00,True
21,S032,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Football,2026-09-17 23:36:00,False
38,S036,61-7344,Laila Mostafa,laila.mostafa@student.guc.edu.eg,IET,Alexandria,Football,2026-09-18 23:36:00,True

In [42]:
before_repeat = len(df)

df = (
    df.sort_values("signed_up_at")
      .drop_duplicates(
          subset=["student_id", "club"],
          keep="last"
      )
)

after_repeat = len(df)

print("Rows before:", before_repeat)
print("Repeated sign-ups removed:", before_repeat - after_repeat)
print("Rows after:", after_repeat)

Rows before: 36
Repeated sign-ups removed: 4
Rows after: 32

### B3. Verify one row per student per club

In [43]:
assert not df.duplicated(
    subset=["student_id", "club"]
).any()

In [44]:
print("Final rows:", len(df))

Final rows: 32

In [45]:
df.to_csv("club_signups_clean.csv", index=False)